server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration:
    access: ${ACCESS_TOKEN_EXPIRATION}
    refresh: ${REFRESH_TOKEN_EXPIRATION}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME} # 데이터베이스 커넥션 이름
    password: ${DB_PASSWORD} # 데이터베이스 커넥션 비밀번호
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: create-drop # 옵션은 필요에 따라 변경
    properties:
      hibernate:
        default_batch_fetch_size: 100 # 지연로딩 최적화를 위한 옵션
        format_sql: true

  output:
    ansi:
      enabled: always

oauth:
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
  apple:
    client-id: ${APPLE_CLIENT_ID}
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    audience: ${APPLE_AUDIENCE}
    private-key: ${APPLE_PRIVATE_KEY} # (-----BEGIN PRIVATE KEY-----, -----END PRIVATE KEY----- 를 제외한 key 문자열을 띄어쓰기 없이 넣어야 합니다)
    redirect-uri: ${APPLE_REDIRECT_URI}

logging:
  file:
    name: ${user.dir}/log/server_log.log # slf4j를 사용할 때 생기는 로그 파일 경로
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace